# Generated by Django 4.2.4 on 2023-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Создатель'),
        ),
    ]
