# Generated by Django 4.2.4 on 2023-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='sending',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отправитель'),
        ),
    ]
