# Generated by Django 4.2.4 on 2023-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_author_sending_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Создатель'),
        ),
    ]
