# Generated by Django 4.2.4 on 2023-09-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_client_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sending',
            name='author',
        ),
    ]
